enum TipoPedido {
  PREPARANDO
  PARTIUENTREGA
  ENTREGUE
}

input PedidoInput {
  id_produto: Int
  dataPedido: String
  parcelas: Int
  id_comprador: Int
  status: String
}

type Pedido {
  id: Int
  id_produto: Int
  dataPedido: String
  parcelas: Int
  id_comprador: Int
  status: String
}

input FiltroInput {
  id: Int
}

type Query {
  pedido(id: Int): Pedido
  pedidos: [Pedido]
}

type Mutation {
  criarPedido(
    id_produto: Int
    dataPedido: String
    parcelas: Int
    id_comprador: Int
    status: String
  ): Pedido
  atualizarPedido(
    id: Int!
    id_produto: Int
    dataPedido: String
    parcelas: Int
    id_comprador: Int
    status: String
  ): Pedido
  deletarPedido(filtro: FiltroInput): Boolean
}
