type Produto {
  id: Int
  nome: String
  urlImagem: String
  descricao: String
  peso: String
  preco: String
  quantidadeEstoque: Int
}

input ProdutoInput {
  nome: String
  urlImagem: String
  descricao: String
  peso: String
  preco: String
  quantidadeEstoque: Int
}

input FiltroInput {
  id: Int
}

type Query {
  produto(id: Int): Produto
  produtos: [Produto]
}

type Mutation {
  criarProduto(
    nome: String
    urlImagem: String
    descricao: String
    peso: String
    preco: String
    quantidadeEstoque: Int
  ): Produto
  atualizarProduto(
    id: Int!
    nome: String
    urlImagem: String
    descricao: String
    peso: String
    preco: String
    quantidadeEstoque: Int
  ): Produto
  deletarProduto(filtro: FiltroInput): Boolean
}
