type Cliente {
  id: Int
  nome: String
  email: String
  cpf: String
  dataNasc: String
  rua: String
  bairro: String
  cidade: String
  estado: String
  pais: String
  cep: String
  numero: Int
}

type Endereco {
  rua: String
  bairro: String
  cidade: String
  estado: String
  pais: String
  cep: String
  numero: Int
}

input ClienteInput {
  nome: String
  email: String
  cpf: String
  dataNasc: String
}

input FiltroInput {
  id: Int
  email: String
}

type Query {
  cliente(id: Int): Cliente
  clientes: [Cliente]
}

type Mutation {
  criarCliente(
    nome: String
    email: String
    cpf: String
    dataNasc: String
    rua: String
    numero: Int
    bairro: String
    cidade: String
    estado: String
    pais: String
    cep: String
  ): Cliente
  atualizarCliente(
    id: Int!
    nome: String
    email: String
    cpf: String
    dataNasc: String
    rua: String
    numero: Int
    bairro: String
    cidade: String
    estado: String
    pais: String
    cep: String
  ): Cliente
  deletarCliente(filtro: FiltroInput): Boolean
}
